### ISSUE TITLE
GET http://localhost:3000/juejin.css net::ERR_ABORTED 404 (Not Found)

### ISSUE THREAD

**Issue by yp199618** [linxsbox/juejin-theme#1]
I run 
```
npx jjsm <myFile>
```
It shows me 
```
GET http://localhost:3000/juejin.css net::ERR_ABORTED 404 (Not Found)
```

**Comment by linxsbox** [comment]
我已经更新了，这边的文档稍后会进行更新

**Comment by linxsbox** [comment]
我已经更新这个工具了，已经正式 publish 到 npm 上了，这边的文档稍后会进行更新

你可以直接使用如下命令，而不需要再克隆这个项目了，感谢~
```base
cd <yourThemeProject>
npx juejin-theme-devtool <yourStyleFile>
```

**Comment by yp199618** [comment]
good job! thanks!

**Comment by yp199618** [comment]
我刚才试了一下,还是报

```
(index):8 GET http://localhost:3000/juejin.css net::ERR_ABORTED 404 (Not Found)
```
![image](https://user-images.githubusercontent.com/24784474/103495127-a5d05980-4e74-11eb-9952-9e5c2eb0fc4b.png)

**Comment by linxsbox** [comment]
1. 之前的版本如果你执行过  link 的话，那么先 unlink
2. 然后尝试删除旧版本项目
3. 尝试使用新的命令执行

npx 机制是先从本地 bin 开始找，然后再到全局，然后再到 publish
